### ISSUE TITLE
Simplify answers with fractionNumbers?

### ISSUE THREAD

**Issue by YannickNeyt** [m8rex/rumbas#21]
Zie bijgevoegd bestand:

[Limietenvanfuncties_eindig_continu_issue.txt](https://github.com/m8rex/rumbas/files/5873319/Limietenvanfuncties_eindig_continu_issue.txt)

Meestal is de displayanswer een kommagetal, terwijl de oplossing wel een breuk is.

**Comment by YannickNeyt** [comment]
.exam uit Numbas die wel werkt:


[question-103297-test-jmedisplay.txt](https://github.com/m8rex/rumbas/files/5873374/question-103297-test-jmedisplay.txt)

**Comment by jhoobergs** [comment]
It seems that DisplayOptions (https://docs.numbas.org.uk/en/latest/simplification.html#display-options) can also be used as 'simplification rules'.

**Comment by jhoobergs** [comment]
Fixed in #61
